services:
  web:
    image: pauliejes/pauliej-web:latest
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - api

  api:
    image: pauliejes/pauliej-api:latest
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - api
