services:
  web:
    image: pauliejes/pauliej-web:latest
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - api

  api:
    image: pauliejes/pauliej-api:latest
    build: ./backend
    ports:
      - "8000:8000"
    environment:
          - NODE_ENV=development