version: '3.8'

services:
  backend:
    image: pauliejes/pauliej-web:latest
    build: ./frontend
    ports:
      - "80:3000"
    depends_on:
      - api

  api:
    image: pauliejes/pauliej-api:latest
    build: ./backend
    ports:
      - "8000:8000"