name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        echo "NEXT_PUBLIC_API_URL=https://pauliej.com:8000" >> ./frontend/.env.production
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push

    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /root/pauliej
          git pull origin main
          docker-compose down
          docker system prune -a --volumes --all --force
          docker-compose pull
          docker-compose up --build -d
# sudo lsof -i :80 | grep -v COMMAND | awk '{print $2}' | xargs -r sudo kill -9